# Generated by cucumber-sinatra. (2013-06-28 22:14:11 +0300)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'app.rb')

require 'capybara'
require 'capybara/cucumber'
require 'capybara/webkit'
require 'rspec'

Capybara.app = App
Capybara.default_driver = :webkit

class AppWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  AppWorld.new
end
